author:
  firstname: "Cameron"
  lastname: "McEwing"
  email: "innovate.with.astrotope@gmail.com"
  homepage: "https://www.astrotope.org"
  phone: "(+64) 21-111-1272"
  github: "Astrotope"
  twitter: "2018Cameronm"
  scholar: ""
  orcid: "0009-0004-8010-6346"
  birth: "February 20, 1969"
  linkedin: "cameron-mcewing-60345315"
  address: "44 Huxley Street, Sydenham, Christchurch, New Zealand, 8023"
  positions:
    - "Full Stack Development"
    - "Cloud Computing"
    - "Artificial Intelligence"
    - "Machine Learning"
    - "Systems Engineering"



